// Run directly: node test/plugin-test.js
const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
assert.equal(manifest.id, 'leomoon-studios.omarchy-parsinegar-express');
assert.equal(manifest.author, 'LeoMoon Studios');
assert.deepEqual(manifest.kinds, ['bar-widget']);
assert.equal(manifest.entryPoints.barWidget, 'Panel.qml');
assert.equal(manifest.barWidget.allowMultiple, false);

const panel = read('Panel.qml');
const menu = read('MenuContent.qml');
const settings = read('SettingsContent.qml');
assert.ok(panel.includes('Ui.WidgetButton {'));
assert.ok(panel.includes('Ui.KeyboardPanel {'));
assert.ok(panel.includes('active: root.opened || root.filePickerActive'));
assert.ok(panel.includes('open: root.opened && !root.filePickerActive'));
assert.ok(panel.includes('source: "MenuContent.qml"'));
assert.ok(!/LibraryAdapter|vendor\/|ParsiNegar\.js/.test(panel));
assert.ok(!/SvgCurve|typr/i.test(panel));
assert.ok(!/SvgCurve(?:Exporter|Adapter|ExportController)|vendor\/typr/i.test(menu));
assert.ok(!/SvgCurve|typr/i.test(settings));
assert.ok(menu.includes('import "LibraryAdapter.js" as Conversion'));
assert.ok(menu.includes('import "ReshaperSettings.js" as Settings'));
assert.ok(menu.includes('component ActionButton: Ui.Button'));
assert.equal((menu.match(/Ui\.Toggle\s*\{/g) || []).length, 0);
assert.ok(!/Controls\.(?:Button|CheckBox)\s*\{/.test(menu));
assert.ok(panel.includes('fittedContentWidth(Style.space(500))'));
assert.ok(menu.includes('Quickshell.clipboardText = output'));
assert.ok(menu.includes('textFormat: TextEdit.PlainText'));
assert.ok(menu.includes('Keys.onEscapePressed'));
assert.ok(!menu.includes('PanelKeyCatcher'));
assert.equal((menu.match(/\bProcess\s*\{/g) || []).length, 1);
assert.equal((menu.match(/\bFileView\s*\{/g) || []).length, 1);
assert.ok(menu.includes('watchChanges: false'));
assert.ok(menu.includes('/.config/leomoon-studios.omarchy-parsinegar-express'));
assert.ok(settings.includes('settings.reset'));
assert.ok(settings.includes('RIAL SIGN'));
assert.ok(settings.includes('ListView {'));
assert.ok(settings.includes('leftPadding: root.controller.uiLanguage === "fa" ? scrollGutter : 0'));
assert.ok(settings.includes('rightPadding: root.controller.uiLanguage === "fa" ? 0 : scrollGutter'));
assert.ok(settings.includes('settingsScroll.ScrollBar.vertical.width + Style.space(6)'));
assert.ok(settings.includes('ScrollBar.vertical.policy: ScrollBar.AsNeeded'));
assert.ok(settings.includes('delegate: Item {'));
assert.ok(settings.includes('width: Math.max(0, parent.width - ligatureList.scrollGutter)'));
assert.ok(settings.includes('settings.title'));
assert.ok(settings.includes('settings.breadcrumb'));
assert.ok(settings.includes('toggle.reverse'));
assert.ok(settings.includes('toggle.video'));
assert.ok(settings.includes('settings.fontNotice'));
assert.ok(settings.includes('import QtQuick.Controls'));
assert.ok(settings.includes('Ui.PanelToolTip {'));
assert.ok(settings.includes('import "InterfaceStrings.js" as Strings'));
assert.ok(menu.includes('import "InterfaceStrings.js" as Strings'));
assert.ok(menu.includes('import "ResourceLimits.js" as Limits'));
assert.ok(settings.includes('settings.languageDescription.'));
assert.ok(settings.includes('settings.languageLabel.'));
assert.ok(settings.includes('columns: 2'));
assert.ok(settings.includes('root.controller.setUiLanguage(modelData)'));
assert.ok(menu.includes('height: Style.space(180)'));
assert.ok(menu.includes('id: exportSection'));
assert.ok(menu.includes('formColumn.implicitHeight > height + 0.5'));
assert.ok(menu.includes('overflowing ? Style.space(18) : 0'));
assert.ok(menu.includes('leftPadding: root.uiLanguage === "fa" ? scrollGutter : 0'));
assert.ok(menu.includes('rightPadding: root.uiLanguage === "fa" ? 0 : scrollGutter'));
assert.ok(menu.includes('Controls.ScrollBar.vertical.policy: Controls.ScrollBar.AsNeeded'));
assert.ok(menu.includes('id: editorHeader'));
assert.ok(menu.indexOf('id: editorHeader') < menu.indexOf('id: formScroll'));
assert.ok(menu.includes('readonly property alias editorPageScroll: formScroll'));
assert.ok(menu.includes('LayoutMirroring.enabled: root.uiLanguage === "fa"'));
assert.ok(menu.includes('id: editorScroll'));
assert.ok(menu.includes('LayoutMirroring.enabled: false'));
assert.ok(menu.includes('id: directionButtons'));
assert.ok(settings.includes('LayoutMirroring.childrenInherit: false'));
assert.ok(settings.includes('LayoutMirroring.enabled: controller.uiLanguage === "fa"'));
assert.ok(menu.indexOf('mode.unicode') < menu.indexOf('mode.compatibility'));
assert.ok(settings.indexOf('toggle.reverse') < settings.indexOf('settings.deleteHarakat'));
for (const key of ['deleteHarakat', 'shiftHarakat', 'deleteTatweel', 'supportZWJ', 'unshapedIsolated', 'supportLigatures']) {
    assert.ok(settings.includes('settings.' + key), key);
}
assert.equal((settings.match(/Ui\.Toggle\s*\{/g) || []).length, 9);
assert.ok(settings.includes('model: root.controller.reshaperMetadata.languages'));
assert.ok(settings.includes('model: root.controller.reshaperMetadata.ligatureGroups'));
assert.ok(settings.includes('root.controller.toggleLigature(modelData.name)'));
for (const source of [panel, read('Typography.qml'), read('LetterBadge.qml')]) {
    assert.ok(!/\b(?:Timer|Process|FileView)\s*\{|Quickshell\.exec/.test(source));
}
for (const source of [menu, settings]) assert.ok(!/\bTimer\s*\{|Quickshell\.exec/.test(source));
for (const file of ['LibraryAdapter.js', 'ParsiNegar.js', 'ReshaperSettings.js', 'InterfaceStrings.js', 'ResourceLimits.js', 'SettingsContent.qml', 'ExportSection.qml', 'SvgCurveExporter.js', 'SvgCurveAdapter.js', 'SvgCurveExportController.qml', 'vendor/js-bidi.js', 'vendor/js-parsi-reshaper.js', 'vendor/typr.js', 'vendor/typr/LICENSE', 'assets/fonts/Vazirmatn[wght].ttf']) {
    assert.ok(fs.statSync(path.join(root, file)).isFile(), file);
}
const curveController = read('SvgCurveExportController.qml');
assert.equal((curveController.match(/\bFileView\s*\{/g) || []).length, 2);
assert.ok(curveController.includes('preload: false'));
assert.ok(curveController.includes('watchChanges: false'));
assert.ok(curveController.includes('function exportTo('));
assert.ok(curveController.includes('Limits.ResourceLimits.assertFontBytes(bytes)'));
assert.match(curveController, /finally\s*\{[\s\S]*fontFile\.path = ""[\s\S]*bytes = null/);
assert.ok(curveController.indexOf('Limits.ResourceLimits.assertFontBytes(bytes)') < curveController.indexOf('Curves.inspect(text, bytes'));
assert.ok(curveController.includes('Curves.inspect(text, bytes, options || {}).missingGlyphs'));
assert.ok(curveController.includes('signal exported(string path, var warnings)'));
assert.ok(curveController.includes('bytes = null'));
assert.doesNotMatch(curveController, /\b(?:Timer|Process|Connections|WorkerScript)\s*\{|Quickshell\.exec|setInterval|setTimeout|fetch\s*\(/);
const exportSection = read('ExportSection.qml');
assert.ok(exportSection.includes('import "ResourceLimits.js" as Limits'));
assert.ok(exportSection.includes('source: "SvgCurveExportController.qml"'));
assert.ok(exportSection.includes('active: false'));
assert.equal((exportSection.match(/\bProcess\s*\{/g) || []).length, 1);
assert.ok(exportSection.includes('["omarchy", "file", "select"'));
assert.ok(exportSection.includes('["/usr/bin/zenity", "--file-selection", "--save"'));
assert.ok(exportSection.includes('"--extensions", "ttf otf ttc"'));
assert.ok(exportSection.includes('"--file-filter=SVG files | *.svg"'));
assert.ok(exportSection.includes('activeMode === "compatibility" ? compatibilityFontPath : unicodeFontPath'));
assert.ok(exportSection.includes('return "Vazirmatn Regular"'));
assert.ok(exportSection.includes('root.controller.statusText'));
assert.ok(exportSection.includes('root.controller.statusWarning ? Color.accent'));
assert.ok(menu.includes('property bool statusWarning: false'));
assert.ok(menu.includes('visible: text !== "" && !exportSection.expanded'));
assert.ok(exportSection.indexOf('export.title') < exportSection.indexOf('export.moreOptions'));
assert.ok(exportSection.indexOf('export.moreOptions') < exportSection.lastIndexOf('export.save'));
assert.doesNotMatch(exportSection, /Quickshell\.clipboardText|SvgCurveAdapter|SvgCurveExporter|vendor\/typr|\b(?:Timer|FileView|WorkerScript)\s*\{|Quickshell\.exec|setInterval|setTimeout|fetch\s*\(/);
console.log('Plugin structure checks passed');
