// Run directly: node test/plugin-test.js
const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
assert.equal(manifest.id, 'leomoon-studios.omarchy-parsinegar-express');
assert.equal(manifest.author, 'LeoMoon Studios');
assert.deepEqual(manifest.kinds, ['bar-widget']);
assert.equal(manifest.entryPoints.barWidget, 'Panel.qml');
assert.equal(manifest.barWidget.allowMultiple, false);

const panel = read('Panel.qml');
const menu = read('MenuContent.qml');
const settings = read('SettingsContent.qml');
const textToolsPage = read('TextToolsPage.qml');
const headerAction = read('HeaderActionButton.qml');
const readme = read('README.md');
assert.ok(fs.existsSync(path.join(root, 'assets/fonts/MaterialSymbolsRounded.ttf')));
assert.ok(fs.existsSync(path.join(root, 'assets/fonts/MaterialSymbols-LICENSE.txt')));
const typography = read('Typography.qml');
assert.ok(typography.includes('MaterialSymbolsRounded.ttf'));
assert.ok(typography.includes('readonly property string iconFamily'));
assert.ok(typography.includes('readonly property string iconExport'));
assert.ok(typography.includes('readonly property string iconTools'));
assert.ok(typography.includes('"\\uf10b"'));
assert.ok(typography.includes('readonly property string iconBack'));
assert.ok(typography.includes('readonly property string iconForward'));
assert.ok(panel.includes('Ui.WidgetButton {'));
assert.ok(panel.includes('Ui.KeyboardPanel {'));
assert.ok(panel.includes('active: root.opened || root.filePickerActive'));
assert.ok(panel.includes('open: root.opened && !root.filePickerActive'));
assert.ok(panel.includes('source: "MenuContent.qml"'));
assert.ok(panel.includes('menuLoader.item.focusCurrentPage()'));
assert.ok(panel.includes('menuLoader.item.focusItem'));
assert.ok(!/LibraryAdapter|vendor\/|ParsiNegar\.js/.test(panel));
assert.ok(!/SvgCurve|typr/i.test(panel));
assert.ok(!/SvgCurve(?:Exporter|Adapter|ExportController)|vendor\/typr/i.test(menu));
assert.ok(!/SvgCurve|typr/i.test(settings));
assert.doesNotMatch(menu, /import "LibraryAdapter\.js"/);
assert.ok(menu.includes('import "EditorDirection.js" as Direction'));
assert.ok(menu.includes('import "ReshaperSettings.js" as Settings'));
assert.ok(menu.includes('import "TextTools.js" as TextTools'));
assert.ok(menu.includes('component ActionButton: Ui.Button'));
assert.ok(menu.includes('component ConvertButton: Ui.Button'));
assert.ok(menu.includes('component ModeCard: Item'));
assert.equal((menu.match(/Ui\.Toggle\s*\{/g) || []).length, 0);
assert.ok(!/Controls\.(?:Button|CheckBox)\s*\{/.test(menu));
assert.ok(panel.includes('fittedContentWidth(Style.space(760))'));
assert.ok(menu.includes('Quickshell.clipboardText = message.output'));
assert.ok(menu.includes('textFormat: TextEdit.RichText'));
assert.ok(menu.includes('horizontalAlignment: TextEdit.AlignRight'));
assert.ok(menu.includes('Keys.onEscapePressed'));
assert.ok(!menu.includes('PanelKeyCatcher'));
assert.equal((menu.match(/\bProcess\s*\{/g) || []).length, 1);
assert.equal((menu.match(/\bFileView\s*\{/g) || []).length, 1);
assert.ok(menu.includes('watchChanges: false'));
assert.ok(menu.includes('/.config/leomoon-studios.omarchy-parsinegar-express'));
assert.ok(settings.includes('settings.reset'));
assert.ok(settings.includes('RIAL SIGN'));
assert.ok(settings.includes('ListView {'));
assert.ok(settings.includes('leftPadding: root.controller.uiLanguage === "fa" ? scrollGutter : 0'));
assert.ok(settings.includes('rightPadding: root.controller.uiLanguage === "fa" ? 0 : scrollGutter'));
assert.ok(settings.includes('settingsScroll.ScrollBar.vertical.width + Style.space(6)'));
assert.ok(settings.includes('ScrollBar.vertical.policy: ScrollBar.AsNeeded'));
assert.ok(settings.includes('delegate: Item {'));
assert.ok(settings.includes('width: Math.max(0, parent.width - ligatureList.scrollGutter)'));
assert.ok(settings.includes('settings.title'));
assert.ok(settings.includes('settings.breadcrumb'));
assert.equal((settings.match(/horizontalAlignment: root\.controller\.uiLanguage === "fa"/g) || []).length, 2);
assert.ok(settings.match(/LayoutMirroring\.enabled: false/g).length >= 3);
assert.ok(settings.includes('toggle.reverse'));
assert.ok(settings.includes('toggle.video'));
assert.ok(settings.includes('settings.fontNotice'));
assert.ok(settings.includes('import QtQuick.Controls'));
assert.ok(settings.includes('Ui.PanelToolTip {'));
assert.ok(settings.includes('import "InterfaceStrings.js" as Strings'));
assert.ok(menu.includes('import "InterfaceStrings.js" as Strings'));
assert.ok(menu.includes('import "ResourceLimits.js" as Limits'));
assert.ok(settings.includes('settings.profileDescription.'));
assert.ok(settings.includes('settings.profileLabel.'));
assert.ok(menu.includes('id: conversionActions'));
assert.ok(menu.includes('layoutDirection: root.uiLanguage === "fa" ? Qt.RightToLeft : Qt.LeftToRight'));
assert.ok(menu.includes('Layout.minimumWidth: Style.space(120)'));
assert.ok(menu.includes('Layout.preferredWidth: Style.space(170)'));
assert.ok(settings.includes('root.controller.setUiLanguage(modelData)'));
assert.ok(menu.includes('height: Style.space(180)'));
assert.ok(menu.includes('id: exportSection'));
assert.ok(menu.includes('formColumn.implicitHeight > height + 0.5'));
assert.ok(menu.includes('overflowing ? Style.space(18) : 0'));
assert.ok(menu.includes('leftPadding: root.uiLanguage === "fa" ? scrollGutter : 0'));
assert.ok(menu.includes('rightPadding: root.uiLanguage === "fa" ? 0 : scrollGutter'));
assert.ok(menu.includes('Controls.ScrollBar.vertical.policy: Controls.ScrollBar.AsNeeded'));
assert.ok(menu.includes('id: editorHeader'));
assert.ok(menu.includes('HeaderActionButton'));
assert.ok(headerAction.includes('Ui.PanelActionButton'));
assert.ok(menu.includes('id: exportHeaderButton'));
assert.ok(menu.includes('id: settingsHeaderButton'));
assert.ok(menu.includes('id: textToolsHeaderButton'));
assert.ok(menu.includes('function openTextTools()'));
assert.ok(menu.includes('page === "tools"'));
assert.ok(menu.includes('function applyTextToolsToSource()'));
assert.ok(menu.includes('var prepared = applyTextToolsToSource()'));
assert.ok(menu.includes('TextTools.TextTools.copyState(result.textTools)'));
assert.ok(menu.includes('TextTools.TextTools.copyState(host ? host.textTools : {})'));
assert.ok(menu.includes('root.openExport()'));
assert.ok(menu.includes('root.openSettings()'));
assert.ok(!menu.includes('width: parent.width\n                    text: root.uiText("button.settings")'));
assert.ok(menu.indexOf('id: editorHeader') < menu.indexOf('id: formScroll'));
assert.ok(menu.includes('readonly property alias editorPageScroll: formScroll'));
assert.ok(menu.includes('LayoutMirroring.enabled: root.uiLanguage === "fa"'));
assert.ok(menu.includes('id: editorScroll'));
assert.ok(menu.includes('LayoutMirroring.enabled: false'));
assert.ok(!menu.includes('id: directionButtons'));
assert.ok(!menu.includes('button.ltr'));
assert.ok(!menu.includes('button.rtl'));
assert.ok(menu.includes('function paragraphLayout'));
assert.ok(menu.includes('Direction.EditorDirection.paragraphLayout(value)'));
assert.ok(menu.includes('requestedLayout.signature !== root.editorDirectionSignature'));
assert.ok(menu.includes('function formattedEditorText'));
assert.ok(menu.includes('text.replace(/\\u200b/g, "")'));
assert.ok(menu.includes('paragraph === "" ? "&#8203;" : escapeHtml(paragraph)'));
assert.ok(menu.includes('Direction.EditorDirection.logicalPosition'));
assert.ok(menu.includes('Direction.EditorDirection.documentPosition'));
assert.ok(menu.includes('function rawEditorText'));
assert.ok(menu.includes('function conversionText'));
assert.ok(menu.includes('return rawEditorText().replace(/\\u2029/g, "\\n")'));
assert.ok(menu.includes('textFormat: TextEdit.RichText'));
assert.ok(menu.includes('alignment === "right" ? "rtl" : "ltr"'));
assert.ok(menu.includes('Accessible.role: Accessible.RadioButton'));
assert.ok(menu.includes('visible: modeCard.hovered && descriptionLabel.truncated'));
assert.ok(menu.includes('objectName: "settingsButton"'));
assert.ok(menu.includes('objectName: "exportButton"'));
assert.ok(settings.includes('objectName: "settingsBackButton"'));
assert.ok(settings.includes('objectName: "ligatureGroupBackButton"'));
assert.ok(settings.includes('LayoutMirroring.childrenInherit: false'));
assert.ok(settings.includes('LayoutMirroring.enabled: controller.uiLanguage === "fa"'));
assert.ok(menu.indexOf('mode.unicode') < menu.indexOf('mode.compatibility'));
assert.ok(menu.includes('mode.unicodeDescription'));
assert.ok(menu.includes('mode.compatibilityDescription'));
assert.ok(settings.indexOf('toggle.reverse') < settings.indexOf('settings.deleteHarakat'));
for (const key of ['deleteHarakat', 'shiftHarakat', 'deleteTatweel', 'supportZWJ', 'unshapedIsolated', 'supportLigatures']) {
    assert.ok(settings.includes('settings.' + key), key);
}
assert.equal((settings.match(/Ui\.Toggle\s*\{/g) || []).length, 9);
assert.ok(settings.includes('model: root.controller.reshaperMetadata.shapingProfiles'));
assert.match(settings, /columns: 3[\s\S]*model: root\.controller\.reshaperMetadata\.shapingProfiles/);
assert.ok(menu.includes('property string shapingProfile: "standardPersianArabic"'));
assert.ok(menu.includes('readonly property bool hebrewProfile: shapingProfile === "hebrew"'));
assert.ok(menu.includes('shapingProfile: shapingProfile'));
assert.ok(menu.includes('autoParagraphDirection: true'));
assert.match(menu, /title: root\.uiText\("mode\.compatibility"\)[\s\S]*enabled: !root\.hebrewProfile/);
assert.ok(settings.includes('root.controller.setShapingProfile(modelData.id, true)'));
assert.ok(settings.includes('settings.hebrewNoticeTitle'));
assert.ok(settings.includes('settings.hebrewNoticeDescription'));
assert.equal((settings.match(/visible: !root\.controller\.hebrewProfile/g) || []).length, 10);
assert.ok(panel.includes('property string shapingProfile: "standardPersianArabic"'));
assert.ok(settings.includes('model: root.controller.hebrewProfile ? [] : root.controller.reshaperMetadata.ligatureGroups'));
assert.ok(settings.includes('root.controller.toggleLigature(modelData.name)'));
assert.match(readme, /Hebrew[^\n]*Unicode-only/);
assert.ok(readme.includes('bypasses JsParsiReshaper and uses JsBidi only'));
assert.ok(readme.includes('this mode does not support Hebrew'));
assert.ok(readme.includes('destination application already supports bidi'));
for (const source of [panel, read('Typography.qml'), read('LetterBadge.qml'), headerAction]) {
    assert.ok(!/\b(?:Timer|Process|FileView)\s*\{|Quickshell\.exec/.test(source));
}
for (const source of [menu, settings]) assert.ok(!/\bTimer\s*\{|Quickshell\.exec/.test(source));
for (const file of ['LibraryAdapter.js', 'ConversionWorker.js', 'ParsiNegar.js', 'ReshaperSettings.js', 'TextTools.js', 'InterfaceStrings.js', 'ResourceLimits.js', 'LocalPath.js', 'BusySpinner.qml', 'HeaderActionButton.qml', 'SectionHeading.qml', 'SettingsContent.qml', 'TextToolsPage.qml', 'ExportSection.qml', 'SvgCurveExporter.js', 'SvgCurveAdapter.js', 'SvgCurveExportController.qml', 'SvgCurveWorker.js', 'vendor/js-bidi.js', 'vendor/js-parsi-reshaper.js', 'vendor/typr.js', 'vendor/typr/LICENSE', 'assets/fonts/Vazirmatn[wght].ttf']) {
    assert.ok(fs.statSync(path.join(root, file)).isFile(), file);
}
const curveController = read('SvgCurveExportController.qml');
assert.equal((curveController.match(/\bFileView\s*\{/g) || []).length, 2);
assert.ok(curveController.includes('preload: true'));
assert.ok(curveController.includes('blockLoading: false'));
assert.ok(curveController.includes('watchChanges: false'));
assert.ok(curveController.includes('function exportTo('));
assert.ok(curveController.includes('Limits.ResourceLimits.assertFontBytes(data)'));
assert.ok(curveController.includes('import "LocalPath.js" as Paths'));
assert.ok(curveController.includes('source: "SvgCurveWorker.js"'));
assert.ok(curveController.includes('curveWorker.sendMessage'));
assert.ok(curveController.includes('signal exported(string path, var warnings)'));
assert.equal((curveController.match(/\bWorkerScript\s*\{/g) || []).length, 1);
assert.doesNotMatch(curveController, /\b(?:Timer|Process|Connections)\s*\{|Quickshell\.exec|setInterval|setTimeout|fetch\s*\(/);
const exportSection = read('ExportSection.qml');
assert.ok(textToolsPage.includes('ScrollView'));
assert.ok(textToolsPage.includes('LayoutMirroring.enabled: controller.uiLanguage === "fa"'));
assert.ok(textToolsPage.includes('TextTools.TextTools.groups(group)'));
assert.ok(textToolsPage.includes('root.controller.toggleTextTool(modelData.id)'));
assert.ok(textToolsPage.includes('font.pixelSize: Style.font.body'));
assert.ok(textToolsPage.includes('objectName: "textToolsBackButton"'));
assert.ok(read('SectionHeading.qml').includes('font.pixelSize: Style.font.body'));
assert.ok(exportSection.includes('import "ResourceLimits.js" as Limits'));
assert.ok(exportSection.includes('import "LocalPath.js" as Paths'));
assert.doesNotMatch(exportSection, /--confirm-overwrite/);
assert.ok(exportSection.includes('source: "SvgCurveExportController.qml"'));
assert.ok(exportSection.includes('active: false'));
assert.equal((exportSection.match(/\bProcess\s*\{/g) || []).length, 1);
assert.ok(exportSection.includes('["omarchy", "file", "select"'));
assert.ok(exportSection.includes('["/usr/bin/zenity", "--file-selection", "--save"'));
assert.ok(exportSection.includes('"--extensions", "ttf otf ttc"'));
assert.ok(exportSection.includes('"--file-filter=SVG files | *.svg"'));
assert.ok(exportSection.includes('activeMode === "compatibility" ? compatibilityFontPath : unicodeFontPath'));
assert.ok(exportSection.includes('return uiText("export.bundledFont")'));
assert.ok(exportSection.includes('objectName: "exportBackButton"'));
assert.ok(exportSection.includes('ScrollView'));
assert.ok(exportSection.includes('exportContent.implicitHeight > height + 0.5'));
assert.ok(exportSection.includes('exportScroll.ScrollBar.vertical.width + Style.space(6)'));
assert.ok(exportSection.includes('ScrollBar.vertical.policy: ScrollBar.AsNeeded'));
assert.match(exportSection, /LayoutMirroring\.enabled: false[\s\S]*export\.alignLeft[\s\S]*export\.alignCenter[\s\S]*export\.alignRight/);
assert.match(exportSection, /columns: 2[\s\S]*mode\.unicode[\s\S]*mode\.compatibility/);
assert.ok(exportSection.includes('root.controller.setConversionMode("unicode")'));
assert.ok(exportSection.includes('root.controller.setConversionMode("compatibility")'));
for (const option of ['fillField', 'precisionField', 'fontIndexField', 'axesField']) assert.ok(exportSection.includes(option));
assert.ok(exportSection.includes('signal backRequested()'));
assert.doesNotMatch(exportSection, /property bool expanded|root\.expanded/);
assert.ok(exportSection.includes('root.controller.statusText'));
assert.ok(exportSection.includes('root.controller.statusWarning ? Color.accent'));
assert.ok(menu.includes('property bool statusWarning: false'));
assert.ok(menu.includes('visible: root.busy || root.statusText !== ""'));
assert.ok(menu.includes('source: "ConversionWorker.js"'));
assert.ok(menu.includes('BusySpinner {'));
assert.ok(exportSection.includes('controller.setExportStatus(uiText("export.processing"), false)'));
assert.ok(exportSection.includes('running: root.preparingExport || exportLoader.active'));
assert.ok(exportSection.indexOf('export.title') < exportSection.indexOf('export.moreOptions'));
assert.ok(exportSection.indexOf('export.moreOptions') < exportSection.lastIndexOf('export.save'));
assert.doesNotMatch(exportSection, /Quickshell\.clipboardText|SvgCurveAdapter|SvgCurveExporter|vendor\/typr|\b(?:Timer|FileView|WorkerScript)\s*\{|Quickshell\.exec|setInterval|setTimeout|fetch\s*\(/);
console.log('Plugin structure checks passed');
